[Local-Data]
local_data_folder=./data
local_output_folder=./output

[Model-Paddle]
det_model_dir=./models/paddle/PP-OCRv5_server_det

[Model-Vietocr]
base_config=./configs/base.yml
recognize_config=./configs/vgg-transformer.yml
recognize_model_weights=./models/vietocr/weights/vgg_transformer.pth
; recognize_model_weights=/mnt/01D5E79859B75510/workspace/tools/VietOCR-Labeling/backend/draft/weights/transformerocr.pth

[Logs]
log_folder=./logs
